# Generated by Django 4.0.2 on 2022-03-31 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Polls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=100)),
                ('option_one', models.CharField(blank=True, max_length=100)),
                ('option_two', models.CharField(blank=True, max_length=100)),
                ('option_three', models.CharField(blank=True, max_length=100)),
                ('option_four', models.CharField(blank=True, max_length=100)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.polls')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_q1', models.CharField(blank=True, max_length=100)),
                ('choice_q2', models.CharField(blank=True, max_length=100)),
                ('choice_q3', models.CharField(blank=True, max_length=100)),
                ('choice_q4', models.CharField(blank=True, max_length=100)),
                ('choice_q5', models.CharField(blank=True, max_length=100)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.polls')),
            ],
        ),
    ]
