# Generated by Django 4.0.2 on 2022-04-20 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_q1',
            new_name='choice',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='poll',
            new_name='poll_name',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='choice_q2',
            new_name='poll_number',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='choice_q3',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='choice_q4',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='choice_q5',
        ),
    ]
