# Generated by Django 4.0.2 on 2022-02-13 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='poll_name',
            field=models.CharField(default='Encuesta:1', max_length=200),
            preserve_default=False,
        ),
    ]
