# Generated by Django 4.0.2 on 2022-04-20 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_choice_q1_choice_choice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice',
            new_name='choice_q1',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='poll_number',
            new_name='choice_q2',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='question',
            new_name='choice_q3',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='poll_name',
            new_name='poll',
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_q4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_q5',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
