# Generated by Django 4.0.2 on 2022-04-26 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_rename_choice_choice_choice_q1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_q1',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='choice_q2',
            new_name='poll_n',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='choice_q3',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='choice_q4',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='choice_q5',
        ),
    ]
