# Generated by Django 4.0.2 on 2022-02-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_polls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='poll_name',
        ),
        migrations.AlterField(
            model_name='question',
            name='option_one',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_two',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
