# Generated by Django 4.0.2 on 2022-02-20 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_remove_question_poll_name_alter_question_option_one_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='poll',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.polls'),
            preserve_default=False,
        ),
    ]
